---
- name: Create host.disk.label
  shell: |
    set -o pipefail
    echo -e "g\nw" | fdisk '{{ host.disk.dev }}'
  changed_when: false

- name: Create partitions
  shell: |
    set -o pipefail
    echo -e "n\n\n\n{{ item.size }}\nt\n\n{{ item.signature }}\nw" | fdisk {{ host.disk.dev }}
  changed_when: false
  loop: '{{ host.disk.partitions|flatten(levels=1) }}'

- name: Format partitions
  command: mkfs.{{ item.fstype }} {{ item.opts }} {{ host.disk.dev }}{{ host.disk.prefix }}{{ item.index }}
  changed_when: false
  loop: '{{ host.disk.partitions|flatten(levels=1) }}'

- name: Mount main partition
  mount:
    path: '{{ host.dir }}{{ item.1.path }}'
    src: '{{ host.disk.dev }}{{ host.disk.prefix }}{{ item.0.index }}'
    fstype: '{{ item.0.fstype }}'
    state: mounted
  loop: '{{ host.disk.partitions|subelements("mounts") }}'
  when: item.0.index == 2

- name: Create btrfs subvolumes
  command: btrfs subvolume create {{ host.dir }}{{ item.1.subvolume }}
  loop: '{{ host.disk.partitions|subelements("mounts") }}'
  when: item.0.fstype == 'btrfs'

- name: Unmount main partition
  mount:
    path: '{{ host.disk.dev }}{{ host.disk.prefix }}{{ item.0.index }}'
    state: unmounted
  loop: '{{ host.disk.partitions|subelements("mounts") }}'
  when: item.0.index == 2

- name: Mount main partition
  mount:
    path: '{{ host.dir }}{{ item.1.path }}'
    src: '{{ host.disk.dev }}{{ host.disk.prefix }}{{ item.0.index }}'
    fstype: '{{ item.0.fstype }}'
    opts: '{{ item.1.opts }}'
    state: mounted
  loop: '{{ host.disk.partitions|subelements("mounts") }}'
  when: item.0.index == 2

- name: Create directories
  file:
    path: '{{ host.dir }}{{ item.1.path }}'
    state: directory
    mode: '0755'
  loop: '{{ host.disk.partitions|subelements("mounts") }}'

- name: Mount partitions
  mount:
    path: '{{ host.dir }}{{ item.1.path }}'
    src: '{{ host.disk.dev }}{{ host.disk.prefix }}{{ item.0.index }}'
    fstype: '{{ item.0.fstype }}'
    opts: '{{ item.1.opts }}'
    state: mounted
  loop: '{{ host.disk.partitions|subelements("mounts") }}'
