---
- name: Install package
  community.general.pacman:
    name: nginx
    update_cache: true

- name: Copy configuration file
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/nginx/
    mode: '0644'
  with_items:
    - nginx.conf
    - conf.d

- name: Start nginx service
  ansible.builtin.systemd:
    state: started
    name: nginx
    enabled: true
