---
- name: Install packages
  pacman:
    name:
      - influxdb
    update_cache: true

- name: Add influxdb user
  user:
    name: influxdb
    group: influxdb
    create_home: false
    system: true

- name: Copy configuration files
  copy:
    src: influxdb.service
    dest: /usr/lib/systemd/system/
    mode: '0644'

- name: Copy nginx configuration
  copy:
    src: nginx/conf.d
    dest: /etc/nginx/
    mode: '0644'

- name: Restart nginx service
  systemd:
    state: restarted
    name: nginx

- name: Start influxdb systemd service
  systemd:
    state: started
    name: influxdb
    enabled: true
