---
- name: Install packages
  pacman:
    name:
      - binutils
      - fakeroot
      - gcc
      - make
      - sudo
    update_cache: true

- name: Create user and add to wheel group
  ansible.builtin.user:
    name: '{{ host.user.wheel.name }}'
    shell: /bin/bash
    groups: wheel
    append: true
    password: '{{ host.user.wheel.password }}'

- name: Allow wheel group to execute any command
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^# %wheel ALL=(ALL) NOPASSWD: ALL'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Copy bash dotfiles
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0644'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - .bashrc
    - .bash_login
    - .bash_login.d
    - .config
    - .editrc
    - .inputrc
    - .ssh
    - bin

- name: Remove bash_profile file
  ansible.builtin.file:
    path: /home/{{ host.user.wheel.name }}/.bash_profile
    state: absent

- name: Copy ssh key
  authorized_key:
    user: '{{ host.user.wheel.name }}'
    key: '{{ lookup("file", "~/.ssh/id_rsa.pub") }}'

- name: Enable ssh-agent service
  become: true
  become_user: '{{ host.user.wheel.name }}'
  become_method: machinectl
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    scope: user
    name: ssh-agent
    enabled: true

- name: Setup autologin
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory
    mode: '0755'
  when: host.user.autologin is defined

- name: Set autologin on tty1
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    mode: '0644'
  when: host.user.autologin is defined
