---
- name: Create hooks directory
  file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: '0755'

- name: Copy xmonad hook
  template:
    src: xmonad.hook.j2
    dest: /etc/pacman.d/hooks/xmonad.hook
    mode: '0644'

- name: Copy configuration files
  copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0644'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - .alacritty.yml
    - .bash_login.d
    - .config
    - .xinitrc
    - .xmonad
    - .Xresources

- name: Copy bin files
  copy:
    src: bin
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0755'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'

- name: Install packages
  pacman:
    name:
      - alacritty
      - calibre
      - chromium
      - dmenu
      - dunst
      - fontconfig
      - gimp
      - keepassxc
      - libxkbcommon
      - libnotify
      - maim
      - mate-calc
      - min
      - numlockx
      - ttf-dejavu
      - xcompmgr
      - xmonad
      - xmonad-contrib
      - xorg-server
      - xorg-xinit
    update_cache: true

- name: Copy xorg files
  copy:
    src: xorg.conf.d
    dest: /usr/share/X11/
    mode: '0644'

- name: Create Xresources directory
  file:
    path: /home/{{ host.user.wheel.name }}/.Xresources.d
    state: directory
    mode: '0755'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'

- name: Add xft settings
  template:
    src: xft.j2
    dest: /home/{{ host.user.wheel.name }}/.Xresources.d/xft
    mode: '0644'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'

- name: Add backlight udev rules
  template:
    src: 80-backlight.rules.j2
    dest: /etc/udev/rules.d/80-backlight.rules
    mode: '0644'

- name: Add user to video group
  user:
    name: '{{ host.user.wheel.name }}'
    groups: video
    append: true

- name: Enable xmonad service
  become: true
  become_user: '{{ host.user.wheel.name }}'
  become_method: machinectl
  systemd:
    daemon_reload: true
    scope: user
    name: xmonad
    enabled: true

- name: Enable xrdb service
  become: true
  become_user: '{{ host.user.wheel.name }}'
  become_method: machinectl
  systemd:
    daemon_reload: true
    scope: user
    name: xrdb
    enabled: true

- name: Enable numlock service
  become: true
  become_user: '{{ host.user.wheel.name }}'
  become_method: machinectl
  systemd:
    daemon_reload: true
    scope: user
    name: numlock
    enabled: true

- name: Enable xcompmgr service
  become: true
  become_user: '{{ host.user.wheel.name }}'
  become_method: machinectl
  systemd:
    daemon_reload: true
    scope: user
    name: xcompmgr
    enabled: true

- name: Enable battery service
  become: true
  become_user: '{{ host.user.wheel.name }}'
  become_method: machinectl
  systemd:
    daemon_reload: true
    scope: user
    name: battery
    enabled: true

- name: Enable battery timer
  become: true
  become_user: '{{ host.user.wheel.name }}'
  become_method: machinectl
  systemd:
    daemon_reload: true
    scope: user
    name: battery.timer
    enabled: true
