---
- name: Run pacstrap
  shell: pacstrap {{ host.dir }} base linux linux-firmware btrfs-progs grub efibootmgr openssh python wpa_supplicant

- name: Generate fstab
  shell: genfstab -U {{ host.dir }} >> {{ host.dir }}/etc/fstab

- name: Install grub
  command: arch-chroot {{ host.dir }} grub-install --target=x86_64-efi

- name: Configure grub
  command: arch-chroot {{ host.dir }} grub-mkconfig -o /boot/grub/grub.cfg

- name: Enable sshd
  command: arch-chroot {{ host.dir }} systemctl enable sshd

- name: Set password to root
  shell: echo root:'{{ host.user.root.password }}' | chpasswd -e -R {{ host.dir }}

- name: Enable ssh root login with password
  lineinfile:
    path: '{{ host.dir }}/etc/ssh/sshd_config'
    regexp: ^#PermitRootLogin
    line: PermitRootLogin yes

- name: Copy systemd network profile
  copy:
    src: '{{ ansible_limit }}/'
    dest: '{{ host.dir }}/etc/systemd/network/'
    mode: 0644

- name: Copy wpa_supplicant configuration
  template:
    src: wpa_supplicant.conf.j2
    dest: '{{ host.dir }}/etc/wpa_supplicant/wpa_supplicant-{{ host.wifi.interface }}.conf'

- name: Enable systemd network
  command: arch-chroot {{ host.dir }} systemctl enable systemd-networkd

- name: Enable systemd wpa_supplicant
  command: arch-chroot {{ host.dir }} systemctl enable wpa_supplicant@{{ host.wifi.interface }}

- name: Enable systemd resolved
  command: arch-chroot {{ host.dir }} systemctl enable systemd-resolved

  notify:
   - reboot
   - wait for restart
