---
- name: Refresh pacman cache
  community.general.pacman:
    name:
      - cups
    update_cache: true

- name: Install samsung drvier
  kewlfft.aur.aur:
    name: samsung-unified-driver
  become: true
  become_user: '{{ host.user.wheel.name }}'

- name: Add systemd-resolved changes
  ansible.builtin.copy:
    src: resolved.conf.d
    dest: /etc/systemd/
    mode: '0644'

- name: Restart systemd-resolved service
  ansible.builtin.systemd:
    state: restarted
    name: systemd-resolved

- name: Copy avahi files
  ansible.builtin.copy:
    src: avahi/services/
    dest: /etc/avahi/services/
    mode: '0644'

- name: Copy cups files
  ansible.builtin.copy:
    src: cups/
    dest: /etc/cups/
    mode: '0644'

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/cups.conf
    mode: '0644'

- name: Restart nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx

- name: Start avahi service
  ansible.builtin.systemd:
    state: started
    name: avahi-daemon
    enabled: true

- name: Start cups service
  ansible.builtin.systemd:
    state: started
    name: cups
    enabled: true
