---
- name: Install packages
  pacman:
    name:
      - samba
    update_cache: true

- name: Copy configuration
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: '0644'

- name: Start smb service
  ansible.builtin.systemd:
    state: started
    name: smb
    enabled: true
