---
- name: Change timezone
  file:
    src: /usr/share/zoneinfo/{{ host.system.timezone }}
    dest: /etc/localtime
    state: link
    force: true

- name: Update timesyncd configuration
  copy:
    src: timesyncd.conf.d
    dest: /etc/systemd/
    mode: '0644'

- name: Enable timedatectl ntp client
  command: timedatectl set-ntp true
  changed_when: false

- name: Set locale
  locale_gen:
    name: '{{ host.system.locale }}'

- name: Set LANG variable
  lineinfile:
    create: true
    path: /etc/locale.conf
    line: LANG={{ host.system.locale }}
    mode: '0644'

- name: Set pacman mirrors
  template:
    src: mirrorlist.j2
    dest: /etc/pacman.d/mirrorlist
    mode: '0644'

- name: Update pacman configuration
  lineinfile:
    path: /etc/pacman.conf
    regexp: ^#Color
    line: Color

- name: Upgrade packages
  pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  pacman:
    name:
      - terminus-font

- name: Copy modprobe changes
  copy:
    src: modprobe.d
    dest: /etc/
    mode: '0644'

- name: Copy hosts
  copy:
    src: hosts
    dest: /etc/
    mode: '0644'

- name: Add vconsole
  template:
    src: vconsole.conf.j2
    dest: /etc/vconsole.conf
    mode: '0644'
