---
- name: Change timezone
  ansible.builtin.file:
    src: /usr/share/zoneinfo/{{ host.system.timezone }}
    dest: /etc/localtime
    state: link
    force: true

- name: Update timesyncd configuration
  ansible.builtin.copy:
    src: timesyncd.conf.d
    dest: /etc/systemd/
    mode: '0644'

- name: Enable timedatectl ntp client
  ansible.builtin.command: timedatectl set-ntp true
  changed_when: false

- name: Set locale
  community.general.locale_gen:
    name: '{{ host.system.locale }}'

- name: Set LANG variable
  ansible.builtin.lineinfile:
    create: true
    path: /etc/locale.conf
    line: LANG={{ host.system.locale }}
    mode: '0644'

- name: Set pacman mirrors
  ansible.builtin.template:
    src: mirrorlist.j2
    dest: /etc/pacman.d/mirrorlist
    mode: '0644'

- name: Update pacman configuration
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: ^#Color
    line: Color

- name: Upgrade packages
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  community.general.pacman:
    name:
      - pacman-contrib
      - python
      - terminus-font

- name: Copy paccache hook
  ansible.builtin.copy:
    src: pacman.d
    dest: /etc/
    mode: '0644'

- name: Add modprobe changes
  ansible.builtin.template:
    src: modprobe.conf.j2
    dest: /etc/modprobe.d/system.conf
    mode: '0644'
  when: host.system.modprobe is defined

- name: Copy hosts
  ansible.builtin.copy:
    src: hosts
    dest: /etc/
    mode: '0644'

- name: Add vconsole
  ansible.builtin.template:
    src: vconsole.conf.j2
    dest: /etc/vconsole.conf
    mode: '0644'
