---
- name: Install rtl_sdr
  pacman:
    name:
      - rtl-sdr
    update_cache: true

- name: Enable non root access
  lineinfile:
    path: /usr/lib/udev/rules.d/10-rtl-sdr.rules
    regexp: 2838
    line: SUBSYSTEMS=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", MODE:="0777"

- name: Copy rtl-wmbus source
  git:
    repo: https://github.com/xaelsouth/rtl-wmbus.git
    dest: /tmp/rtl-wmbus
    depth: 1
    version: master

- name: Make rtl-wmbus
  community.general.make:
    chdir: /tmp/rtl-wmbus

- name: Move bin file
  command: mv /tmp/rtl-wmbus/build/rtl_wmbus /usr/bin/
  changed_when: false

- name: Install wmbusmeters
  git:
    repo: https://github.com/weetmuts/wmbusmeters.git
    dest: /tmp/wmbusmeters
    depth: 1
    version: master

- name: Patch wmbusmeters
  lineinfile:
    path: /tmp/wmbusmeters/src/meter_apator08.cc
    regexp: total_water_consumption_m3_ /=
    state: absent

- name: Configure wmbusmeters
  command: ./configure
  changed_when: false
  args:
    chdir: /tmp/wmbusmeters

- name: Install wmbusmeters
  community.general.make:
    chdir: /tmp/wmbusmeters
    target: install

- name: Copy wmbusmeters configuration file
  template:
    src: wmbusmeters.conf.j2
    dest: /etc/wmbusmeters.conf
    mode: '0644'

- name: Copy wmbusmeters systemd file
  copy:
    src: wmbusmeters.d
    dest: /etc/
    mode: '0644'

- name: Start wmbusmeters systemd file
  systemd:
    state: started
    name: wmbusmeters
    enabled: true
