---
- name: Install packages
  community.general.pacman:
    name:
      - nfs-utils
    update_cache: true

- name: Copy configuration
  ansible.builtin.copy:
    src: exports.d
    dest: /etc/
    mode: '0644'

- name: Start nfs service
  ansible.builtin.systemd:
    state: started
    name: nfs-server
    enabled: true
