---
- name: Install package dependencies
  community.general.pacman:
    name:
      - nodejs-lts-gallium
    update_cache: true

- name: Install zigbee2mqtt
  kewlfft.aur.aur:
    name: zigbee2mqtt-git
  become: true
  become_user: '{{ host.user.wheel.name }}'

- name: Restore copy
  ansible.builtin.unarchive:
    src: '{{ host.zigbee2mqtt.backup }}'
    dest: /
    remote_src: true

- name: Copy nginx configuration
  ansible.builtin.copy:
    src: nginx/conf.d
    dest: /etc/nginx/
    mode: '0644'

- name: Restart nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx

- name: Start systemd service
  ansible.builtin.systemd:
    state: started
    name: zigbee2mqtt
    enabled: true
