---
- name: Install packages
  pacman:
    name:
      - zigbee2mqtt
    update_cache: true

- name: Copy nginx configuration
  ansible.builtin.copy:
    src: nginx/conf.d
    dest: /etc/nginx/
    mode: '0644'

- name: Restart nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx

- name: Install systemd
  ansible.builtin.systemd:
    state: started
    name: zigbee2mqtt
    enabled: true
