---
- name: Install packages
  community.general.pacman:
    name:
      - mosquitto
    update_cache: true

- name: Copy configuration file
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: /etc/mosquitto/
    mode: '0644'

- name: Start mosquito systemd service
  ansible.builtin.systemd:
    state: started
    name: mosquitto
    enabled: true
