---
- name: Install packages
  pacman:
    name:
      - chromium
      - gimp
      - perl-image-exiftool
      - ansible
      - sshpass
      - calibre
      - rsync
      - gnome-calculator
    update_cache: yes

- name: Copy custom bin files
  copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/bin/
    mode: 0755
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - aur.sh
