---
- name: Install package
  pacman:
    name:
      - virtualbox
      - virtualbox-host-modules-arch
    update_cache: true

  notify:
    - reboot

- name: Force to run hooks
  meta: flush_handlers

- name: Wait for restart
  pause:

- name: Add host network adapter
  command: vboxmanage hostonlyif create
  changed_when: false
