---
- name: Refresh pacman cache
  community.general.pacman:
    name:
      - cups
      - cups-pdf
    update_cache: true

- name: Copy cups files
  ansible.builtin.copy:
    src: cups/
    dest: /etc/cups/
    mode: '0644'

- name: Copy printers files
  ansible.builtin.template:
    src: printers.conf.j2
    dest: /etc/cups/printers.conf
    mode: '0644'

- name: Start cups service
  ansible.builtin.systemd:
    state: started
    name: cups
    enabled: true
