---
- name: Install packages
  community.general.pacman:
    name:
      - ansible
      - aws-cli
      - inetutils
      - p7zip
      - pv
      - rsync
      - sshpass
      - unrar
      - unzip
      - usbutils
      - which
      - zip
    update_cache: true
