---
- name: Install packages
  community.general.pacman:
    name:
      - ansible
      - aws-cli
      - inetutils
      - p7zip
      - pv
      - rsync
      - sshpass
      - unrar
      - unzip
      - usbutils
      - which
      - zip
    update_cache: true

- name: Copy custom files
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0755'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - bin
