---
- name: Install package
  pacman:
    name:
      - tmux
      - xclip
    update_cache: true

- name: Copy configuration files
  copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0644'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - bin
    - .config
    - .bashrc.d
    - .tmux.conf
    - .tmux

- name: Enable tmux service
  become: true
  become_user: '{{ host.user.wheel.name }}'
  become_method: machinectl
  systemd:
    state: started
    daemon_reload: true
    scope: user
    name: tmux
    enabled: true

- name: Fix permissions
  file:
    path: /home/{{ host.user.wheel.name }}/.tmux
    owner: '{{ host.user.wheel.name }}'
    group: '{{ host.user.wheel.name }}'
    recurse: true
    mode: '0755'
