---
- name: Refresh pacman cache
  pacman:
    name:
      - nodejs
      - npm
    update_cache: yes

- name: Copy configuration files
  copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: 0644
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - .eslintrc.yml
