---
- name: Remove packages
  pacman:
    name:
      - vim
    state: absent
    extra_args: --recursive

- name: Install package
  pacman:
    name: gvim
    update_cache: true
    extra_args: --noconfirm

- name: Copy dotfile
  copy:
    src: .vimrc
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0644'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'

- name: Install submodules
  git:
    repo: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/.vim/pack/plugins/start/{{ item | regex_search('[^/]+(?=.git)') }}
    depth: 1
    force: true
    version: master
  with_items: '{{ host.vim.plugins }}'

- name: Fix permissions
  file:
    path: /home/{{ host.user.wheel.name }}/.vim
    owner: '{{ host.user.wheel.name }}'
    group: '{{ host.user.wheel.name }}'
    recurse: true
    mode: '0755'

- name: Set EDITOR
  lineinfile:
    path: /etc/environment
    line: EDITOR=vim
