---
- name: Install packages
  pacman:
    name:
      - home-assistant
      - python-httpx
      - python-defusedxml
      - python-mutagen
      - python-zeroconf
      - python-psycopg2
    update_cache: true

- name: Copy nginx configuration
  copy:
    src: nginx/conf.d
    dest: /etc/nginx/
    mode: '0644'

- name: Change systemd file
  lineinfile:
    path: /usr/lib/systemd/system/home-assistant.service
    regexp: ^After=
    line: After=network.target postgresql.service

- name: Restore copy
  unarchive:
    src: /wd2/backup/hass/2021-03-13-20.17.11.tar.gz
    dest: /var/lib/
    remote_src: true

- name: Copy bin
  copy:
    src: bin/
    dest: /usr/bin/
    mode: '0755'

- name: Restart nginx service
  systemd:
    state: restarted
    name: nginx

- name: Start systemd service
  systemd:
    state: started
    name: home-assistant
    enabled: true
