---
- name: Install packages
  community.general.pacman:
    name:
      - home-assistant
      - python-httpx
      - python-defusedxml
      - python-mutagen
      - python-zeroconf
      - python-psycopg2
      - python-pycountry
    update_cache: true

- name: Copy nginx configuration
  ansible.builtin.copy:
    src: nginx/conf.d
    dest: /etc/nginx/
    mode: '0644'

- name: Change systemd file
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/home-assistant.service
    regexp: ^After=
    line: After=network.target postgresql.service

- name: Restore copy
  ansible.builtin.unarchive:
    src: '{{ host.home_assistant.backup }}'
    dest: /var/lib/
    remote_src: true

- name: Copy bin
  ansible.builtin.copy:
    src: bin/
    dest: /usr/bin/
    mode: '0755'

- name: Restart nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx

- name: Create hass postgresql database
  ansible.builtin.command: createdb hass
  changed_when: false
  become: true
  become_user: postgres

- name: Start systemd service
  ansible.builtin.systemd:
    state: started
    name: home-assistant
    enabled: true
