---
- name: Install rbenv
  git:
    repo: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/.rbenv
    depth: 1
    version: master
  with_items: '{{ host.rbenv.git }}'

- name: Install plugins
  git:
    repo: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/.rbenv/plugins/{{ item | regex_search('[^/]+(?=.git)') }}
    depth: 1
    version: master
  with_items: '{{ host.rbenv.plugins }}'

- name: Copy configuration files
  copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: '0644'
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - .bash_login.d
    - .gemrc
    - .rspec
    - .rubocop.yml
